---
# Add additional stages in the order of execution here, and then under the job:include: key
stages:
  - "lint"
  - "pylint"
  - "test"

if: "type IN (pull_request)" # Add in "branch" as an option if desired for branch testing as well
language: "python"
services:
  - "docker"

env:
  matrix:
    - "PYTHON_VER=3.6"
    - "PYTHON_VER=3.7"
    - "PYTHON_VER=3.8"
    - "PYTHON_VER=3.9"
before_script:
  - "pip install invoke poetry toml"
  - "invoke build --nocache"
script:
  - "invoke pytest"

jobs:
  include:
    - stage: "lint"
      env:
        - "INVOKE_LOCAL=True"
      before_script:
        - "pip install invoke toml black bandit pydocstyle flake8 yamllint pylint"
      script:
        - "invoke black"
        - "invoke bandit" # Bandit fails to function on > Py3.8 https://github.com/PyCQA/bandit/issues/639
        - "invoke pydocstyle"
        - "invoke flake8"
        - "invoke yamllint"
    - stage: "pylint"
      before_script:
        - "pip install invoke poetry toml"
        - "invoke build --nocache"
      script:
        - "invoke pylint"
